name: WindCharge
version: 1.0
author: Devruso
main: com.devruso.windCharge.WindCharge
api-version: 1.21

commands:
  getitem:
    description: "Gives the player 90 Wind Charges"
    usage: "/getitem"
    permission: windcharge.getitem
  setwindcharge:
    description: "Sets the properties of the Wind Charge"
    usage: "/setwindcharge <property> <value>"
    permission: windcharge.setwindcharge
  sethome:
    description: "Seta uma home no local atual"
    usage: "/sethome <nome>"
  teleport:
    description: "Teletransporta para uma home salva"
    usage: "/teleport <nome>"
  teleportcd:
    description: "Define o cooldown para o teletransporte de home"
    usage: "/teleportcd <tempo_em_segundos>"
  teleportparticles:
    description: "Ativa/Desativa a exibição de partículas ao teletransportar"
    usage: "/teleportparticles"
permissions:
  windcharge.getitem:
    description: "Allows the player to get Wind Charges"
    default: true
  windcharge.setwindcharge:
    description: "Allows the player to set properties of the Wind Charge"
    default: true
  home.sethome:
    description: "Marks the current location as a home. It's important to specify its name"
    default: true
  home.teleport:
    description: "Lets the user teleport to one of it previous homes"
    default: true

